name = "WRFSimulator"
uuid = "7cf07a3c-20f2-407b-aa4c-7987a21194b3"
authors = ["PeterSomkuti <peter.somkuti@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
